### ISSUE TITLE
对于KL loss有以下疑问

### ISSUE THREAD

**Issue by Hoantrbl** [Emiyalzn/GraphDE#1]
感谢作者如此精彩的工作！在参考代码过程有以下疑问：

在`Instantiations of the Recognition Model`中，提到利用graphde-a来对环境的$e$来进行优化，我找到以下部分的具体代码：

![image](https://user-images.githubusercontent.com/48271804/204736944-3c8f53ec-1d52-48f1-9729-6b19a69ba76f.png)

疑问如下：

`e_inferred_logprob` 为什么要concat起来呢？最后计算的时候，用了一个手动设置prior的阈值来进行先验处理，为什么不是利用`e_inferred`进行处理？

这些在论文没有得到解释，烦请作者指点！期待您的回复！

**Comment by Emiyalzn** [comment]
您好，此处将二者cat起来是pytorch中nn.KLDivLoss(..)函数的需求，prior的阈值是计算KL loss所必须手动设置的量，但在进行reweighting的时候，我们还是用e_inferred进行计算的。

**Comment by Hoantrbl** [comment]
> nn.KLDivLoss(..)

谢谢作者回答，可能我没有表达清楚我的意思，`nn.KLDivLoss(..)`只需要输入目标分布以及目前分布即可进行计算，这是我知悉的，询问concat的操作问题可细化如下：

1.  为什么要进行`e_in_log`以及`e_out_log`的计算，为什么是减去`divider`，这个在论文中没有体现，想询问这种操作的意义
2. prior具体的意义是什么呢？为什么把`e_in_log`与`1 - self.prior_ratio`对应起来呢？这个同样在论文没有体现操作

<img width="980" alt="image" src="https://user-images.githubusercontent.com/48271804/204748496-0d71fca1-b08d-4b0c-8b5f-2a9faae23069.png">

这一部分的代码是否指代了公式10的内容，因为感觉prior阈值的设置`self.prior_ratio`有点突兀，从loss计算上，应该是`e_inferred`作为目标分布的。

<img width="423" alt="image" src="https://user-images.githubusercontent.com/48271804/204749151-82765f30-4b51-4163-8e52-c9e3b6bc24fc.png">

烦请作者指点！期待您的回复！

@Emiyalzn

**Comment by Emiyalzn** [comment]
您好,`self.prior_ratio`即KL loss中的$p(\mathbf e)$，在附录中有阐述我们将KL loss的先验设为了数据集的biased ratio。之后关于减去divider这一操作，理论上来说也可以直接对e_infer取log（因为torch的KL函数需要输入分布的log distribution），在训练过程中由于数值稳定性的问题在此处用logsumexp的方式计算divider并减去。您可以发现`log(e_inferred)=logprob-divider`。

**Comment by Hoantrbl** [comment]
> 您好,`self.prior_ratio`即KL loss中的$p(\mathbf e)$，在附录中有阐述我们将KL loss的先验设为了数据集的biased ratio。之后关于减去divider这一操作，理论上来说也可以直接对e_infer取log（因为torch的KL函数需要输入分布的log distribution），在训练过程中由于数值稳定性的问题在此处用logsumexp的方式计算divider并减去。您可以发现`log(e_inferred)=logprob-divider`。

谢谢作者的回答！
